name: youtube_downloader_master
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  font_awesome_flutter: ^10.2.1
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  flutter_insta: ^1.0.1
  device_info_plus: ^10.1.0
  dio: ^5.4.3+1
  lottie: ^3.0.0
  permission_handler: ^11.3.1
  html: ^0.15.4
  youtube_explode_dart: ^2.2.1
  flutter_downloader: ^1.11.7
  path_provider: ^2.1.3
  flutter_spinkit: ^5.2.1
  http: ^1.0.0
  image_gallery_saver: ^2.0.3
  percent_indicator: ^4.2.3
  connectivity_plus: ^6.0.3
  flutter_svg: ^2.0.10+1
  flutter_svg_provider: ^1.0.7
  flutter_local_notifications: ^17.1.2
  awesome_notifications: ^0.9.3+1
  internet_connection_checker: ^1.0.0+1
  flutter_animate: ^4.5.0
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1
  slider_button: ^2.1.0

dependency_overrides:
  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  image_path: "assets/download.png"  # Path to your icon image

flutter_native_splash:
  color: "#ffffff"
  image: assets/download.png
  color_dark: "#000000" # Dark mode background color
  image_dark: assets/download.png # Dark mode image
  android: true # Enable splash screen for Android
  android_gravity: center 
  android_12:
    image: assets/download.png
    icon_background_color: "#ffffff"
    image_dark: assets/download.png
    icon_background_color_dark: "#000000"

  web: false
  ios: true # Enable splash screen for iOS
  ios_content_mode: center # Center the image on iOS

flutter:

  uses-material-design: true

  assets:
    - assets/Bulk-Image-Downloader-Free-Download.jpg
    - assets/download.json
    - assets/logo-development.jpg
    - assets/download.png
